name: Build and test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gembcior/d-ral-docker
    strategy:
      matrix:
        platform:
          - cortex-m3
          - cortex-m4

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Run CMake Workflow
        run: |
          cmake --workflow --preset ${{ matrix.platform }}

      - name: Install build artifacts
        run: |
          cmake --install ./output/build/RelWithDebInfo/${{ matrix.platform }}

      - name: Prepare environment
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip install -r tests/requirements.txt

      - name: Run tests
        run: |
          . .venv/bin/activate
          robot --pythonpath ./tests/libraries:./tests/resources:./utils --variable PLATFORM:${{ matrix.platform }} tests

      - name: Archive tests results
        uses: actions/upload-artifact@v4
        with:
          name: robot-framework-results-${{ matrix.platform }}
          path: |
            output.xml
            log.html
            report.html
          retention-days: 7
